---

- name: yum update
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - "*"

- name: install module
  yum: 
    name: "{{item}}"
    state: present
  loop: "{{ install_packages_list | default([], true) }}"

- name: systemd enable
  systemd:
    name: "{{item}}"
    enabled: yes
  loop: "{{enabled_packages_list | default([], true) }}"

- name: systemd disable
  systemd:
    name: "{{item}}"
    enabled: no
  loop: "{{disabled_packages_list | default([], true) }}"

- name: set timezone
  timezone:
    name: "{{ local_timezone }}"
  
- name: set locale
  command: "localectl set-locale LANG={{ local_locale }}"

- name: set keymap
  command: "localectl set-keymap {{ locale_keymap }}"

- name: set hostname
  hostname:
    name: "{{ linux_hostname }}"

- name: IPv6 disabled
  sysctl:
    state: present
    name: "{{ item }}"
    value: "1"
    sysctl_set: no
    reload: no
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Disable SELinux
  selinux:
    state: disabled

- name: create operation users
  user: 
    name: "{{ item.key }}"
    password: "{{ item.value.password }}"
    groups: "{{ item.value.groups }}"
    shell: /bin/bash
    home: "/home/{{ item.key }}"
    state: present
  loop: "{{ user_newusers|dict2items }}"

- name: snmpd.conf file copy
  template:
    src: "snmpd.conf.j2"
    dest: "/etc/snmp/snmpd.conf"
    owner: root
    group: root
    mode: 0600